### ISSUE TITLE
Losing Focus With No Editor Crashes Redcar

### ISSUE THREAD

**Issue by jvantuyl** [rdp/redcar-save-all-on-lose-focus#1]
When I have no files open and cause the window to lose focus, Redcar crashes with an error because it can't seem to find the editor view.

Full output is available in [this gist](https://gist.github.com/664636/51d52865f6520b301f318a55cadd1019f898853d).

**Comment by stevenheidel** [comment]
Something similar happens even when I have files open, although I haven't looked at the stack trace yet.

**Comment by shimaore** [comment]
This is actually the same issue as issue #2, and the fix is to replace the line:
   modified_edit_tabs = tabs.select {|t| t.edit_view.document.modified? }
with:
   modified_edit_tabs = tabs.select {|t| defined?(t.edit_view) && t.edit_view.document.modified? }

**Comment by jvantuyl** [comment]
This looks pretty dead.  Closing...
